name: TransWriter CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: TransWriter.sln
      Test_Project_Path: TransWriter.Tests/TransWriter.Tests.csproj
      Wap_Project_Directory: TransWriter.Package
      Wap_Project_Path: TransWriter.Package/TransWriter.Package.wapproj

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore Dependencies
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=${{ matrix.configuration }}

    - name: Build Solution
      run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }}

    - name: Run Unit Tests
      run: dotnet test $env:Test_Project_Path --configuration ${{ matrix.configuration }} --no-build --logger "trx;LogFileName=test_results.trx"

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: '**/TestResults/*.trx'

    - name: Package Application
      run: msbuild $env:Wap_Project_Path /p:Configuration=${{ matrix.configuration }} /p:AppxBundle=Always /p:AppxBundlePlatforms="x86|x64"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MSIX Package
        path: ${{ env.Wap_Project_Directory }}/AppPackages

    - name: Create GitHub Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        files: ${{ env.Wap_Project_Directory }}/AppPackages/**/*.msix
